### ISSUE TITLE
GFProgressBar giving out error

### ISSUE THREAD

**Issue by Censored1375** [ionicfirebaseapp/getwidget#184]
** I get the following error when calling the GFProgressBar ** 
```
════════ Exception caught by animation library ═════════════════════════════════════════════════════
The following _TypeError was thrown while notifying listeners for AnimationController:
type 'int' is not a subtype of type 'double'

When the exception was thrown, this was the stack: 
#0      _GFProgressBarState.initState.<anonymous closure>.<anonymous closure> (package:getwidget/components/progress_bar/gf_progress_bar.dart:139:17)
#1      State.setState (package:flutter/src/widgets/framework.dart:1240:30)
#2      _GFProgressBarState.initState.<anonymous closure> (package:getwidget/components/progress_bar/gf_progress_bar.dart:138:15)
#3      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:137:19)
#4      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:798:5)
...
The AnimationController notifying listeners was: AnimationController#778da(▶ 0.000)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: type 'int' is not a subtype of type 'double'

════════ Exception caught by animation library ═════════════════════════════════════════════════════
type 'int' is not a subtype of type 'double'
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: type 'int' is not a subtype of type 'double'

════════ Exception caught by animation library ═════════════════════════════════════════════════════
type 'int' is not a subtype of type 'double'
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: type 'int' is not a subtype of type 'double'

════════ Exception caught by animation library ═════════════════════════════════════════════════════
type 'int' is not a subtype of type 'double'
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**My code**
`GFProgressBar(
                        animateFromLastPercentage: true,
                        animation: true,
                        progressBarColor: Colors.greenAccent,
                        circleStartAngle: 0.0,
                        type: GFProgressType.circular,
                        progressHeadType: GFProgressHeadType.circular,
                        circleWidth: 90.0,
                        percentage: 0.5,
                        width: 100,
                        radius: 90,
                        backgroundColor : Colors.black26,
                      ),`
Pls help i have had this for nearly a week now

**Comment by Sandipkakadiya** [comment]
This issue has been fixed in new release [1.2.3](https://pub.dev/packages/getwidget/versions/1.2.3)
